# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Billy Schmidt
tagline:          No idea what I'm doing
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Billy Schmidt
  url:            http://billyschmidt.io
  email:          bs@billyschmidt.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
