# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Billy Schmidt
tagline:          My Tech Blog (and other stuff)
url:              http://billyschmidt.org
paginate:         1
baseurl:          /
author:
  name:           Billy Schmidt
  url:            https://twitter.com/bigdatadevops
  email:          bs@billyschmidt.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/billyschmidt/poole

exclude: ['vendor']