# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          http://billyschmidt.github.io/poole/
author:
  name:           Billy Schmidt
  url:            http://billyschmidt.io
  email:          bs@billyschmidt.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
